---
- name: Setup devbox environment
  hosts: localhost
  connection: local
  gather_facts: yes
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  roles:
    - common
    - git
