---
- name: Test common role
  hosts: all
  gather_facts: yes
  become: yes
  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install basic packages for testing
      ansible.builtin.package:
        name:
          - curl
          - sudo
        state: present

    - name: Create test user
      ansible.builtin.user:
        name: testuser
        shell: /bin/bash
        create_home: yes
        home: /home/testuser
      register: test_user

    - name: Set HOME environment variable for test user
      ansible.builtin.set_fact:
        ansible_env:
          HOME: "/home/testuser"
          PATH: "/usr/local/bin:/usr/bin:/bin"

    - name: Install Node.js (as volta alternative for testing)
      ansible.builtin.package:
        name: nodejs
        state: present
      when: ansible_os_family == "Debian"

    - name: Install npm
      ansible.builtin.package:
        name: npm
        state: present
      when: ansible_os_family == "Debian"

  tasks:
    - name: Include common role
      ansible.builtin.include_role:
        name: common
      vars:
        # Skip homebrew tasks in Docker
        common_skip_homebrew: true
