name: CI

'on':
  push:
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint yamllint

      - name: Install ansible collections
        run: |
          ansible-galaxy collection install -r requirements.yml

      - name: Run yamllint
        run: |
          yamllint .

      - name: Run ansible-lint
        run: |
          ansible-lint

      - name: Run ansible-playbook syntax check
        run: |
          ansible-playbook --syntax-check site.yml

      - name: Run ansible-playbook dry run
        run: |
          ansible-playbook --check --diff -i localhost, site.yml
